### PR TITLE
Fix how to handle env vars on examples

### PR DESCRIPTION
**Pull request by jsanz**
When running examples you are forced to set up environment variables so the arguments parsing is not meaningful. Review the way I'm proposing to handle this (there are other ways) and if you agree, please apply the same workflow to the rest of the examples so they can be run passing the credentials as parameters.

### CODE REVIEW

**Comment by oriolbx** [comment]
Going to apply the same workflow to the rest of examples

**Comment by jsanz** [comment]
@alrocar, before merging this fix to the examples... do you think there's anything we need to do? like tagging or deploying this to `pip` later, etc

**Comment by alrocar** [comment]
Merge and I'll take care. Next time I'll write a document with the steps for publishing a new version:

- Update NEWS file with the changes
- Update version 1.1.1 to 1.1.2 everywhere (specially in setup.py and the doc folder)
- Merge/tag/publish to pip

Thanks!

**Comment by jsanz** [comment]
@alrocar added those changes, please review :smile:

**Comment by alrocar** [comment]
🇪🇸

**Comment by jsanz** [comment]
added a line to the `NEWS` and merged, all yours @alrocar for update on `pip`

**Pull request merged**
